import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const isProduction = process.argv.includes('--production');
const envPath = resolve('.env');
const outPath = resolve('src/environments/environment.ts');
const required = [
  'API_URL',
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_DATABASE_URL',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

// Local dev reads from a .env file; CI/hosting (e.g. Vercel) injects the same
// keys as real environment variables. A local .env, when present, takes
// precedence over process.env.
const fileEnv = existsSync(envPath) ? parseEnvFile(readFileSync(envPath, 'utf8')) : {};
const env = { ...process.env, ...fileEnv };

const missing = required.filter((key) => !env[key]);
if (missing.length > 0) {
  console.error(
    `Missing required env vars: ${missing.join(', ')}. ` +
      'Set them in .env for local dev or as environment variables in your host.',
  );
  process.exit(1);
}

// The environments dir holds only generated files (gitignored), so it may not
// exist in a clean checkout (e.g. CI/Vercel). Create it before writing.
mkdirSync(dirname(outPath), { recursive: true });

writeFileSync(
  outPath,
  `// Generated by scripts/generate-env.mjs from .env — do not edit directly.
export const environment = {
  production: ${isProduction},
  apiUrl: '${env['API_URL']}',
  supabaseUrl: '${env['SUPABASE_URL']}',
  supabaseAnonKey: '${env['SUPABASE_ANON_KEY']}',
  mapsApiKey: '${env['MAPS_API_KEY'] ?? ''}',
  mapsMapId: '${env['MAPS_MAP_ID'] ?? ''}',
  firebase: {
    apiKey: '${env['FIREBASE_API_KEY']}',
    authDomain: '${env['FIREBASE_AUTH_DOMAIN']}',
    databaseURL: '${env['FIREBASE_DATABASE_URL']}',
    projectId: '${env['FIREBASE_PROJECT_ID']}',
    storageBucket: '${env['FIREBASE_STORAGE_BUCKET']}',
    messagingSenderId: '${env['FIREBASE_MESSAGING_SENDER_ID']}',
    appId: '${env['FIREBASE_APP_ID']}',
    measurementId: '${env['FIREBASE_MEASUREMENT_ID'] ?? ''}',
  },
} as const;
`,
);

console.log(`Generated ${outPath} from .env`);

function parseEnvFile(content) {
  const result = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const eq = trimmed.indexOf('=');
    if (eq === -1) {
      continue;
    }
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    const isQuoted =
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"));
    if (isQuoted) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}
